#!/usr/bin/env node
"use strict";

const fs   = require("fs");
const path = require("path");

const ROOT       = path.join(__dirname, "..");
const DATA_FILE  = path.join(ROOT, "blog-data.json");
const BLOG_DIR   = path.join(ROOT, "blog");

// Same date stamp as scripts/build-version.js, so blog pages regenerated by
// `npm run build:blog` alone still point at fresh cache-bust URLs.
const _now    = new Date();
const _pad    = n => String(n).padStart(2, "0");
const ASSET_V = `${_now.getFullYear()}${_pad(_now.getMonth() + 1)}${_pad(_now.getDate())}`;

const CSS_LINKS = `  <link rel="stylesheet" href="/css/brand-tokens.css?v=${ASSET_V}" />
  <link rel="stylesheet" href="/css/base.css?v=${ASSET_V}" />
  <link rel="stylesheet" href="/css/components.css?v=${ASSET_V}" />
  <link rel="stylesheet" href="/css/layout.css?v=${ASSET_V}" />
  <link rel="stylesheet" href="/css/blog-post.css?v=${ASSET_V}" />`;

const JS_FOOTER = (post) => `<script src="/js/footer.js?v=${ASSET_V}" defer></script>
<script src="/js/script.js?v=${ASSET_V}" defer></script>
  <script src="/api-static/jarvis-widget.js?v=hi-jarvis-20260507" data-endpoint="/api/jarvis-chat" data-fallback-endpoint="/api/jarvis-chat" data-live-endpoint="wss://jarvis.kingofyadav.in/api/ws/public" data-enquiry-endpoint="https://jarvis.kingofyadav.in/api/public-enquiry" data-signup-endpoint="https://jarvis.kingofyadav.in/api/public-signup" data-title="Jarvis AI" data-subtitle="Ask Jarvis about King Yadav and the website." data-site-line="Explore identity, writing, services, ventures, and collaboration." defer></script>
  <script src="/js/blog-translate.js?v=${ASSET_V}" defer></script>`;

function buildHead(post) {
  const absUrl = `https://kingofyadav.in${post.url}`;
  const title  = `${post.title} | Amit Ku Yadav`;
  const desc   = post.excerpt || post.description || "";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escHtml(title)}</title>
  <meta name="description" content="${escAttr(desc)}" />
  <meta name="author" content="Amit Ku Yadav" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="index, follow" />
  <link rel="canonical" href="${escAttr(absUrl)}" />
  <meta property="og:title" content="${escAttr(title)}" />
  <meta property="og:description" content="${escAttr(desc)}" />
  <meta property="og:image" content="https://kingofyadav.in/og-image.png" />
  <meta property="og:url" content="${escAttr(absUrl)}" />
  <meta property="og:site_name" content="Amit Ku Yadav" />
  <link rel="icon" href="/favicon/favicon.ico" />
  <link rel="apple-touch-icon" href="/favicon/apple-touch-icon.png" />
  <link rel="manifest" href="/manifest.json" />
${CSS_LINKS}
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": ${JSON.stringify(title)},
  "description": ${JSON.stringify(desc)},
  "author": {"@type": "Person", "name": "Amit Ku Yadav", "url": "https://kingofyadav.in"},
  "publisher": {"@type": "Person", "name": "Amit Ku Yadav", "url": "https://kingofyadav.in"},
  "url": ${JSON.stringify(absUrl)},
  "mainEntityOfPage": {"@type": "WebPage", "@id": ${JSON.stringify(absUrl)}}${post.date ? `,\n  "datePublished": ${JSON.stringify(post.date)}` : ""}
}
<\/script>
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escAttr(title)}" />
  <meta name="twitter:description" content="${escAttr(desc)}" />
  <meta name="twitter:image" content="https://kingofyadav.in/og-image.png" />
  <meta name="twitter:creator" content="@kingofyadav_in" />
  <meta name="twitter:site" content="@kingofyadav_in" />
</head>`;
}

function escHtml(s) { return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }
function escAttr(s) { return String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;"); }

async function rewriteExistingPost(filePath, post) {
  try {
    await fs.promises.access(filePath);
  } catch {
    return false;
  }

  let content = await fs.promises.readFile(filePath, "utf8");

  const headEnd = content.indexOf("</head>");
  if (headEnd === -1) return false;

  const bodyContent = content.slice(headEnd + 7);
  const footerIdx = bodyContent.lastIndexOf('<footer class="site-footer');
  if (footerIdx === -1) {
    await fs.promises.writeFile(filePath, buildHead(post) + "\n" + bodyContent, "utf8");
    return true;
  }

  const beforeFooter = bodyContent.slice(0, footerIdx);
  const newContent = buildHead(post) + "\n" + beforeFooter +
    `<footer class="site-footer glass" data-footer></footer>

<button id="backToTop" aria-label="Back to top">
  <svg viewBox="0 0 24 24"><polyline points="18 15 12 9 6 15"/></svg>
</button>
${JS_FOOTER(post)}
</body>
</html>`;

  await fs.promises.writeFile(filePath, newContent, "utf8");
  return true;
}

async function main() {
  const posts = JSON.parse(await fs.promises.readFile(DATA_FILE, "utf8"));
  let updated = 0, skipped = 0;

  for (const post of posts) {
    if (!post.url) { skipped++; continue; }
    const relPath = post.url.replace(/^\//, "");
    const filePath = path.join(ROOT, relPath);
    if (!filePath.startsWith(BLOG_DIR)) { skipped++; continue; }

    if (await rewriteExistingPost(filePath, post)) {
      console.log(`  updated: ${relPath}`);
      updated++;
    } else {
      console.log(`  skipped: ${relPath} (file not found)`);
      skipped++;
    }
  }

  console.log(`\nbuild:blog — ${updated} updated, ${skipped} skipped`);
}

main().catch(err => { console.error(err); process.exit(1); });
